// Automatically generated by astro-icon
// a0b56b7fec2c548cd142b9f2a078ddaf53ad52cae1788059ca842a7ca9c50446

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "telegram-full"
		| "vk";
}